from pydantic import BaseModel, Field

class Rvc_model_meta(BaseModel):
    name : str = Field(title="rvc model name", max_length=20)
    batch_size : int = Field(title="model train batch size", gt=0)
    save_epoch : int = Field(title="save epoch number that save current train weight", gt=0)
    total_epoch : int = Field(title="total training epoch", gt=0)
    image : str | None = Field(default=None, title="model ambassador image")
    image_name : str | None = Field(default=None, title="model ambassador image name")
    data_set_id : str = Field(title="data set id that was used at model training")
    test_script : str | None  = Field(default=None, title="test sound that generated by model") 

class Tts_model_meta(BaseModel):
    name : str = Field(title="tts model name", max_length=20)
    batch_size : int = Field(title="model train batch size", gt=0)
    save_epoch : int = Field(title="save epoch number that save current train weight", gt=0)
    total_epoch : int = Field(title="total training epoch", gt=0)
    image : str | None = Field(default=None, title="model ambassador image")
    image_name : str | None = Field(default=None, title="model ambassador image name")
    data_set_id : str = Field(title="data set id that was used at model training")
    test_script : str | None = Field(default=None, title="test sound that generated by model")  
    language : str  = Field(title="language of training data set",pattern="^(EN|JP|KR)$") 
    
class Rvc_data_set_meta(BaseModel):
    data_set_name : str = Field(title="rvc data set name", max_length=20)
    description : str = Field(title="description of data set's feature", max_length=200)
    data_set : str = Field(title="data set save path")

class Tts_data_set_meta(BaseModel):
    data_set_name : str = Field(title="tts data set name", max_length=20)
    description : str = Field(title="description of data set's feature", max_length=200)
    data_set : str = Field(title="data set save path")
    file_list : str = Field(title="file list save path")
    config  : str = Field(title="config file save path")

    
    