version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    networks:
      - db_net
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    networks:
      - db_net
    ports:
      - 8084:8080
networks:
  db_net:
    driver: bridge